### ISSUE TITLE
드롭다운 메뉴 관련 버그

### ISSUE THREAD

**Issue by kiwitreekor** [LiteHell/theseed-skin-buma#1]
https://theseed.io/thread/RL4WUUQ1rY7zLGNtNMUfgL
심각해지면 한번 누르면 10번 왕복하고 열림

**Comment by LiteHell** [comment]
커밋 bf8ab598f2c7d0f80ce8dfc6f981fe36d90cfdf9 에서 해결됐습니다. 기다리시면 됩니다.
