### ISSUE TITLE
사문의 기여내역 링크가 좆같이 보임

### ISSUE THREAD

**Issue by Tenpower** [LiteHell/theseed-skin-buma#10]
위키의 아무 사문이나 들어가서 기여내역 탭으로 들어가면

https://www.alphawiki.org/contribution/author/사용자:LiteHell/document

이렇게 보이는데

https://www.alphawiki.org/contribution/author/LiteHell/document

이렇게 수정부탁합니다.

**Comment by Hoto-Cocoa** [comment]
제목이 좀...

**Comment by LiteHell** [comment]
fixed

**Comment by Tenpower** [comment]
제목수정
