### ISSUE TITLE
여전히 해결되지 못한 오류 수정 요청

### ISSUE THREAD

**Issue by Rollable** [LiteHell/theseed-skin-buma#106]
2022년 12월경에 발생한 아래 두 문제가 발생하여 해결 요청을 드렸으나 최근에 확인해본 결과 아직도 해결되지 않고 존재합니다. 확인하시고 빠른 시일 내에 해결하여 주시면 감사드리겠습니다.

- [라이선스 페이지 오류](https://github.com/LiteHell/theseed-skin-buma/issues/95)
- [리스트 표시 문제](https://github.com/LiteHell/theseed-skin-buma/issues/96)

**Comment by Rollable** [comment]
현재 리스트 표시 문제는 해결된 것으로 보이며 라이선스 페이지 오류만 이뤄지면 될 거 같습니다.

**Comment by navyCarpet** [comment]
라이선스 페이지 오류라는 게 ul이 왼쪽으로 쏠렸다는 뜻인가요?

**Comment by Rollable** [comment]
네 맞습니다.

**Comment by Rollable** [comment]
![Uploading IMG_3521.jpeg…]()

**Comment by Rollable** [comment]
![IMG_3521](https://github.com/user-attachments/assets/eb570e31-f479-44c9-95d2-0ce0d0534884)

**Comment by Rollable** [comment]
![IMG_3522](https://github.com/user-attachments/assets/359220da-e1c4-4e1a-a91a-7c8dad1feac6)
