### ISSUE TITLE
스킨 오류

### ISSUE THREAD

**Issue by Gyotong** [LiteHell/theseed-skin-buma#109]
# 사용환경
 * 브라우저 : (e.g. Firefox 107.0/Chrome 109.0.5414.7)
 * 운영체제 : (Android 10/Windows 10/Ubuntu 22.04)

# 버그 설명
알파위키에서 buma 스킨으로 바꾸면 흰 화면만 나타납니다.

**Comment by LiteHell** [comment]
이건 저도 원인을 바로 알 수가 없어서... 파악하는 대로 조치하겠습니다.

**Comment by navyCarpet** [comment]
contribution_author_link, contribution_ip_link methods가 삭제되고 contribution_link로, contribution_author_link_discuss, contribution_ip_link_discuss가 삭제되고 contribution_link_discuss로 methods가 변경되었습니다.

**Comment by navyCarpet** [comment]
contribution_link, contribution_link_discuss는 이전처럼 username이나 ip를 받는 것이 아닌 uuid를 parameter로 받고 있습니다.

**Comment by LiteHell** [comment]
16eebe074f9191cf3ee1c24b6936f49ed1a1cf46 에서 수정했습니다. 한 번에 수정됐으면 좋겠네요..

**Comment by navyCarpet** [comment]
https://github.com/LiteHell/theseed-skin-buma/commit/16eebe074f9191cf3ee1c24b6936f49ed1a1cf46#diff-6e53f2a6d5c36e538ae219360d1802e32cc0082942fa155c185e0549ccf5e808R295
skin page data에서 사용자 문서 주인의 uuid를 줘야 하는데 현재로선 skin data에서는 확인할 수가 없습니다.

**Comment by LiteHell** [comment]
아... 저 부분을 미처 자세히 못 봤네요. 795c82667be417114c840bd4b225feb21ca007b5 에서 수정했습니다.

**Comment by navyCarpet** [comment]
난독화된 데이터 중에선 사용자 문서 주인의 uuid를 주고 있으므로 곧 skin data에도 추가되지 않을까 싶네요

**Comment by LiteHell** [comment]
> 난독화된 데이터 중에선 사용자 문서 주인의 uuid를 주고 있으므로 곧 skin data에도 추가되지 않을까 싶네요

이것까지 반영했습니다. 제가 놓친 부분이 없다면 곧 해결되지 않을까... 싶네요.

**Comment by Rollable** [comment]
[이 문제들도 해결 부탁드립니다.](https://github.com/LiteHell/theseed-skin-buma/issues/106)

**Comment by Rollable** [comment]
또한 현재 buma 스킨 사용 시 일반 문서 접근이 불가능합니다.

**Comment by LiteHell** [comment]
흰 화면만 나타나던 버그 고쳤습니다.



> [이 문제들도 해결 부탁드립니다.](https://github.com/LiteHell/theseed-skin-buma/issues/106)

이건 추후 시간이 날때 해결하겠습니다.
