### ISSUE TITLE
스킨 오류

### ISSUE THREAD

**Issue by RENAISSANCE-lll** [LiteHell/theseed-skin-buma#111]
# 사용환경
 * 브라우저 : (e.g. Firefox 107.0/Chrome 109.0.5414.7)
 * 운영체제 : (Android 10/Windows 10/Ubuntu 22.04)

# 버그 설명
https://github.com/LiteHell/theseed-skin-buma/issues/109
위 이슈와 동일한 문제가 나타나고 있으며, 사용 환경과 무관하게 buma 스킨으로 변경하기만 하면 오류가 발생하여 브라우저와 운영 체제는 따로 기재하지 않았습니다.

**Comment by LiteHell** [comment]
Vue 의존성 버전 문제로 추측되며, 해당 추측이 맞다면 코드 수정을 통한 해결이 어려움. @namu-theseed 의 도움이 필요함.

**Comment by RENAISSANCE-lll** [comment]
더시드포럼에 이슈를 남겨야 하나요?

**Comment by LiteHell** [comment]
그건 좀 애매해서 저도 뭐라 답변드려야 될 지 모르겠네요.
