### ISSUE TITLE
해결되지 않은 라이선스 페이지 오류 

### ISSUE THREAD

**Issue by Rollable** [LiteHell/theseed-skin-buma#118]

**Comment by navyCarpet** [comment]
css build가 되지 않은 것 같습니다.

**Comment by Rollable** [comment]
어디가 문제인건지.. 스킨 업데이트를 진행해도 해결되지가 않는데 도대체 어디가 문제인걸까요..

**Comment by Rollable** [comment]
> css build가 되지 않은 것 같습니다.

아까 수정하신 부분이 제대로 머지 되지 않았다는 말씀이신가요?

**Comment by navyCarpet** [comment]
> > css build가 되지 않은 것 같습니다.
> 
> 아까 수정하신 부분이 제대로 머지 되지 않았다는 말씀이신가요?

스킨에는 문제 없고 서버에서 css build를 하여야 변경된 css가 반영됩니다.

**Comment by Rollable** [comment]
아 네 확인했습니다.

**Comment by navyCarpet** [comment]
현재 해결되었습니다.
