### ISSUE TITLE
수정 요청 부탁드립니다.

### ISSUE THREAD

**Issue by Tenpower** [LiteHell/theseed-skin-buma#14]
https://www.alphawiki.org/thread/3hSxGwh6JtzvXqDTwFKYYR#129

1. 129번 쓰레드와 같이 링크 넣으면 박스 밖으로 튀어 나옵니다. 수정 부탁드립니다.

2. ([한자]링크 초록색)이 뜨는데 한자도 해결할 수 없나요?

**Comment by LiteHell** [comment]
한자는 원래 그런데... 외부링크할때 외해서 外에요.
엔하위키 미러가 저렇게 표시했을텐데...

**Comment by LiteHell** [comment]
아이콘으로 바꿔줄 수 있긴 함. 시간날때 바꿔드리죠.

**Comment by LiteHell** [comment]
1번 수정 2번 계획없음(약간 곤란함)
