### ISSUE TITLE
개선 요청3

### ISSUE THREAD

**Issue by Tenpower** [LiteHell/theseed-skin-buma#15]
https://www.alphawiki.org/RecentChanges

지금 당장 모바일로 알파위키 최근 바뀜을 보면 개선이 필요하다고 생각합니다.

**Comment by LiteHell** [comment]
스킨 업데이트 후에도 불편하다면 이슈 다시 열어주세요. 아직 알파위키에 스킨이 업데이트되지 않았습니다.
