### ISSUE TITLE
부마 스킨 하단에 다음과 같은 안내문구 추가

### ISSUE THREAD

**Issue by wikified** [LiteHell/theseed-skin-buma#17]
'본 위키를 이용하는 행위는 본 위키의 규정, 면책조항 등을 포함한 일체의 이용 규약에 동의하는 것으로 간주합니다'

알파위키의 관련 토론 중 필요성이 있다 보여 이슈 요청합니다.

**Comment by LiteHell** [comment]
@wikified namu한테 footer_text 설정을 요청해주시기 바랍니다.
