### ISSUE TITLE
아무래도 알파위키 색을 맞추는게 좋을 것 같아요.

### ISSUE THREAD

**Issue by kiwitreekor** [LiteHell/theseed-skin-buma#18]
로고는 분홍색인데, 메인 컬러가 초록색이다보니까 뭔가 매칭이 안되네요... 알파용 리브레 색깔처럼 하면 어울릴것같습니다.

**Comment by kiwitreekor** [comment]
전용이 아니면 알파버전을 따로 만들어서 색을 바꾸던지 하면 좋겠네요.

**Comment by 2du** [comment]
알파위키 전용 스킨은 아닌걸로 압니다

**Comment by kiwitreekor** [comment]
그건 알았는데 재목 수정이 안되네요.

**Comment by Hoto-Cocoa** [comment]
제목 수정 가능합니다.

**Comment by kiwitreekor** [comment]
리버티도 색 맞춰 나오는데 안 될게 있을까요?

**Comment by pseol2190** [comment]
동의합니다. Liberty 스킨의 경우도 알파위키의 대표색인 #ABCDEF가 적용되어 있는데, 알파위키 한정으로 이 스킨의 대표색을 #ABCDEF로 변경하는 것이 좋을 듯 합니다. 근데 그 전에 위키 별로 CSS 적용이 가능한지 모르겠네요.

**Comment by pseol2190** [comment]
@kiwitreekor 제목 옆에 있는 'Edit' 버튼을 눌러 보시기 바랍니다.

**Comment by pseol2190** [comment]
일단 Buma 스킨 자체가 _알파위키 전용_으로 만들어진 것은 아닙니다.

**Comment by Katinor** [comment]
@pseol2190 추가기능 제안 정도로 생각하는것도 괜찮겠네요. 넓게보면 사용자 CSS까지 도달할수도 있겠고요.

**Comment by pseol2190** [comment]
@Katinor 근데 사용자 CSS(개인 CSS) 기능 추가는 theseed-skin-buma의 기능이라기 보다는 [the seed](https://forum.theseed.io/) 엔진에 먼저 추가되어서 지원해야 할 기능이 아닐까요?

**Comment by Hoto-Cocoa** [comment]
@kiwitreekor 그걸 왜 저분한테 따지고 계시죠;

**Comment by Hoto-Cocoa** [comment]
색 하나 바꿔주겠다고 업뎃 두번 올리는 귀찮은 작업을 하는 것보다 그냥 현행 유지가 낫다고 생각합니다. 현 색상도 나쁜편은 아니고요.

**Comment by Hoto-Cocoa** [comment]
namu님이 the seed 엔진에 Config 기능을 넣어서 색상을 설정해 주시는 것이 아니라면 딱히 LiteHell님이 달가워 할 그런 요청은 아닌 것 같습니다. 알파위키 색 하나 바꿔주겠다고 Branch 하나 뽑아서 업뎃 하나 만들 때마다 CSS 컴파일 두번 하고 Commit 두번 하고 저라면 싫을 것 같은데요.

**Comment by pseol2190** [comment]
그래서 Liberty 스킨에 #ABCDEF가 들어갔나요?

**Comment by kiwitreekor** [comment]
@Hoto-Cocoa Bulma 라이브러리 쪽에서 정해져 있는 색상이라 한 번 커스텀해주면 업데이트마다 다시 컴파일할 필요는 없을 것 같습니다.
알파위키에서 이미 대문을 #ABCDEF로 맞춰놔서 초록색과는 조화가 잘 안됩니다.

**Comment by kiwitreekor** [comment]
@pseol2190 네.

**Comment by Hoto-Cocoa** [comment]
알파위키 전용 스킨이 아닌데 알파위키 색에 맞추게 되면 알파위키 색 버전이 따로 나오게 되죠. 그럼 CSS 업데이트마다 컴파일 해주는게 맞습니다. 조화가 안되는건 키위트리님 생각 같고 전 이 불편을 감수하면서까지 업데이트를 만들 가치가 있다고 보이지 않습니다.

**Comment by Hoto-Cocoa** [comment]
말 예쁘게 하시네요. 리드미라도 한번 읽고 오세요.

2018년 9월 19일 (수) 23:15, kiwitreekor <notifications@github.com>님이 작성:

**Comment by kiwitreekor** [comment]
@Hoto-Cocoa 그래서 수정했는데 꼭 그렇게 말씀하셔야 하셨는지요.

**Comment by LiteHell** [comment]
상의후 방식 결정하겠음.

**Comment by LiteHell** [comment]
@LiteHell 일단 빌드 스크립트를 생각중...

**Comment by pseol2190** [comment]
참나 ㅋㅋㅋㅋ 내가 여기서 이런 말 안 하려고 했는데 저분 나한테만 저러는 거 아니구나 ㅋㅋㅋ

**Comment by pseol2190** [comment]
* 내가 맨날 시비 턴다고? 지금 이렇게 돌아다니면서 정작 시비터는 건 누군데?
* CSS 컴파일하기 귀찮아? Identify는 어따 팔아먹고?
* 이젠 나한테 그러는 게 모자라서 kiwitreekor님한테까지 그러냐?

**Comment by Hoto-Cocoa** [comment]
Identify가 그렇게 중요하면 직접 Fork해서 하세요. 왜 당신이 귀찮은 일 남 시킵니까? 돌아다니면서 시비터는게 아니라 알림 설정해뒀는데 뭐가 와서 그냥 할 말 한거고, 뭔데 반말이세요.

**Comment by pseol2190** [comment]
* http://www.kimdirector.co.kr/bbs/view.php?id=webdesign&no=290
* http://www.kimdirector.co.kr/bbs/view.php?id=webdesign&no=137
* http://www.detra.org/down/html_date/33.브랜드%20아이덴티티의.pdf

**Comment by LiteHell** [comment]
@Hoto-Cocoa @pseol2190 
1. 저놈이 잘못했다 != 나도 욕해도 된다.
1. 저놈이 띠겁게 말했다 != 나도 띠겁게 말해도 된다.
1. 저놈이 전에도 좆같이 굴었다 != 고로 나도 좆같이 굴어도 된다.

누가 잘했고 잘못했고를 떠나서 서로간에 최소 가식적인 예의라도 갖추고 말합시다.
* 적절한 예시 : CSS 컴파일하는 게 귀찮을 수도 있지만 위키의 아이덴티티를 살리는 것이 더 중요하다고 생각해요. 그쪽은 어떻게 생각하시나요?
* 부적절한 예시 : 꼬우면 포크해

**Comment by LiteHell** [comment]
내가 잘했네 니가 잘했네를 떠나서 제발 예의를 갖춰주세요.

**Comment by LiteHell** [comment]
한 번만 더 지랄하면 둘 다 차단할거임.

**Comment by Hoto-Cocoa** [comment]
@pseol2190 관련 없는 내용입니다. 가져오신 내용은 "자신이 직접 Brand Identify를 만들어서 사이트 등에 반영" 할 때의 이야기고, 지금은 "외부 인력"이 "무상"으로 "전혀 관련 없는 것"을 만들어서 가져다 쓰는건데 감놔라 배놔라 하는거라서요.

**Comment by pseol2190** [comment]
[#](https://www.alphawiki.org/w/적반하장)

**Comment by Tenpower** [comment]
음 상의가 될까요?

**Comment by Hoto-Cocoa** [comment]
지금 이 상황은, LiteHell님이 the seed engine을 사용하는 위키에서 사용하라고 만들어둔 스킨을 알파위키에서 가져가 사용하는 입장인 상태에서 "우리들 색이랑 맞지 않으니 바꿔달라"라고 요구를 해오는 것입니다.

**Comment by LiteHell** [comment]
@Tenpower 하의도 있는데 상의가 안 될리가요.

**Comment by pseol2190** [comment]
갑자기 무엇?

**Comment by Tenpower** [comment]
그리고 깃헙은 나만 지랄하는 공간이 아닙니다.

**Comment by centrair-hoya** [comment]
코코아씨는 지적 받고 태도를 고쳤는데 Pseol씨는 태도가 그대로네요.

**Comment by wikified** [comment]
이슈트래커는 청와대 국민청원이 아닙니다.

**Comment by LiteHell** [comment]
일단 빌드 스크립트로 해결방안 결정했고요, 더 이상의 싸움은 무의미하니 이슈 잠그겠습니다.

**Comment by PtrKR** [comment]
알파위키 폐쇄로 무의미해진 이슈
