### ISSUE TITLE
주시문서 기능 추가 요청

### ISSUE THREAD

**Issue by Tenpower** [LiteHell/theseed-skin-buma#19]
더시드엔진에 주시문서 기능이 추가되었네요. senkawa만 추가된 것 같은데 여기 buma에도 추가 요청합니다. 감사합니다.

주시문서 링크 : https://alphawiki.org/member/starred_documents

**Comment by LiteHell** [comment]
메모입니다, 무시하세요.

```
star_count
starred
```

**Comment by LiteHell** [comment]
고침.

**Comment by LiteHell** [comment]
내 문서함 깜박함

**Comment by LiteHell** [comment]
resolved.
