### ISSUE TITLE
저기요

### ISSUE THREAD

**Issue by bumabugjebo** [LiteHell/theseed-skin-buma#22]
사진 크기가 이상하고 게시판 링크가 없고 어두운 테마가 이상하고 나무픽스 안되고(180630.0버전 사용중) 관리자링크 없다고요

**Comment by bumabugjebo** [comment]
저기요 문서함 링크는 어디로 도망갔나요

**Comment by Hoto-Cocoa** [comment]
사진 크기 - 문서 편집을 하시기 바랍니다.
어두운 테마 - 개선중입니다.
나무픽스 - 나무픽스에 제보해주세요.
관리자 메뉴 - 관리 권한 보유자에게만 표시됩니다.

**Comment by Hoto-Cocoa** [comment]
말 조금만 예쁘게 해주시면 감사하겠습니다.

**Comment by Git0xf** [comment]
@bumabugjebo 게시판 링크 없음: 나무위키에 맞춰 제작된 스킨이 아니기 때문에 없습니다.
관리자 링크 없음: 권한 보유자에게만 표시되도록 설정하였습니다.

**Comment by bumabugjebo** [comment]
#3 센카와 스킨은 잘 나옵니다 부마만 이상합니다

**Comment by Hoto-Cocoa** [comment]
나무위키 토론이 아닙니다. #3이 어떤 것을 의미하는지 말씀해주세요.

**Comment by bumabugjebo** [comment]
그 이 이쓔의 3번째 발언 말입니다.

**Comment by Hoto-Cocoa** [comment]
senkawa 스킨은 나무위키 전용이기 때문에 게시판 등이 정상적으로 나올 수밖에 없습니다.

**Comment by bumabugjebo** [comment]
아니 사진크기 말하는겁니다.

**Comment by Hoto-Cocoa** [comment]
3번째 내용이 어떤건지 말씀해달라는 이야기입니다. 제가 보는 3번째 내용은 말을 조금만 예쁘게 해달라는 Comment거든요.

**Comment by Hoto-Cocoa** [comment]
어떤 문서에서 발생하는지 말씀해주셔야 해결을 할 수 있을 것 같습니다.

**Comment by bumabugjebo** [comment]
모든 문서 말입니다. 그리고

사진 크기 - 문서 편집을 하시기 바랍니다.
어두운 테마 - 개선중입니다.
나무픽스 - 나무픽스에 제보해주세요.
관리자 메뉴 - 관리 권한 보유자에게만 표시됩니다.

내용이 3번째 아닙니까 이 이쓔의 사진 크기가 이상하고 게시판 링크가 없고 어두운 어쩌구가 1번째 아닙니까!

**Comment by wikified** [comment]
무슨 소린지 모르겠습니다.

**Comment by bumabugjebo** [comment]
님 발언 전의 발언 전의 발언 하신 분에게 얘기중입니다.

**Comment by Git0xf** [comment]
@bumabugjebo Issue는 이'슈'라고 읽습니다. 또한 GitHub에서는 뭐가 어떻게 어디서 문제를 발생시키는지를 명확하게 기술해주셔야 해결이 가능합니다.

**Comment by Hoto-Cocoa** [comment]
어떤 문서에서 문제가 발생하는지 말씀해주시면 확인해보도록 하겠습니다.

**Comment by zlzleking** [comment]
제발 이슈에서 싸우지 마세요

이슈 제시하신분은 무엇이 어떻게 문제인지 스크린샷과 링크 등으로 제보해주시고

메인테이너는 말 가지고 그러지 마시고

양쪽 다 말 좀 곱게 하세요

**Comment by bumabugjebo** [comment]
사진 크기가 모든 문서에서 도를 넘어서 크게 이상하고 어두운 테마가 배경은 안 까매지고 딴문서가면 어두운테마 없어지고 나무픽스 안되고(180630.0버전 사용중)권한있을 때도 관리자링크가 집에서 자고있고 문서함 링크는 도망갔습니다.

**Comment by wikified** [comment]
결국 그건 동어반복이잖아요.

**Comment by bumabugjebo** [comment]
더 자세하게 설명한거 아닙니까!

**Comment by centrair-hoya** [comment]
확인해보니까 모든 그림이 그런 것도 아니니 설명이 부족한게 맞습니다. 관리자 링크가 안 나오신다는 말을 하시니 나무위키 관리자 이신거 같은 데 나무위키는 관리를 원래 그렇게 하나요?

**Comment by wikified** [comment]
뭐 저런 사람이 관리자를 하니까 나무위키가 꺼무위키 나라, 좆무위키 소리를 듣는 거죠.

**Comment by bumabugjebo** [comment]
아주 예전에 사퇴했는데 링크가 안뜬다는 말을 많이 들었습니다.

**Comment by Git0xf** [comment]
권한이 없으면 관리자 메뉴는 원래 안 뜨는 게 정상입니다.

**Comment by wodud98** [comment]
;;;;

**Comment by bumabugjebo** [comment]
근데 예전에 권한있ㄴ은 사람이 링크 안뜬다는 말을

**Comment by bumabugjebo** [comment]
많이 들어서

**Comment by bumabugjebo** [comment]
안뜬다고 한거 아닙니까!!

**Comment by centrair-hoya** [comment]
@LiteHell https://screenshots.firefox.com/BAjI5q58WJs47A1z/namu.wiki

이미지 증상 확인바람

**Comment by wikified** [comment]
이슈트래커는 자신의 문제점 경험을 올리는 곳이지 풍문을 제보하는 곳이 아닙니다.

**Comment by bumabugjebo** [comment]
아니 대부분이란 말입니까 근데 나머지는 경험 아닙니까!!!!!!

**Comment by bumabugjebo** [comment]
이미지가 대부분 크게

**Comment by bumabugjebo** [comment]
나온다고요.

**Comment by Hoto-Cocoa** [comment]
관리자 메뉴는 최근에 추가 된 기능입니다.

**Comment by bumabugjebo** [comment]
스크린샷 바랍니다 그래야 그 이슈우 제보를 취소 가능합니다.

**Comment by Git0xf** [comment]
buma 스킨의 관리자 메뉴는 PR #21에서 추가되었고, 나무위키에 반영된지는 아직 24시간도 지나지 않았습니다. 제보자님께서 나무위키 관리자가 아닌 이상 해당 관리자 메뉴의 존재 여부를 확인할 수 없는 것이 당연합니다.

**Comment by bumabugjebo** [comment]
그럼 이거 하나때문에 다시 관리자를 지원해야합니까????????? 당신 나무위키 관리자 입니까??

**Comment by centrair-hoya** [comment]
관리자가 제보해주겠죠.

**Comment by kpjhg0124** [comment]
권한없으면 당연히 관리자메뉴 안뜨죠

**Comment by bumabugjebo** [comment]
근데 없었던 걸로 알고 있었던거 제가 옛날에 얘기한거 보면 알수 있잖습니까!!!!!!

**Comment by centrair-hoya** [comment]
그건 님탓이구요

**Comment by Hoto-Cocoa** [comment]
나무냐고 물으시면 그럴 확률은 50%라고 제가 말씀을 드릴 수 있겠습니다만은 이것은 다음 기회에 설명을 드리도록 하겠습니다.

**Comment by Hoto-Cocoa** [comment]
최근 업데이트로 추가되었습니다.

**Comment by 2du** [comment]
이슈가 이슈? 깔깔

**Comment by bumabugjebo** [comment]
뭐죠

**Comment by yeoncomi** [comment]
@2du 이슈를 봤슈?

**Comment by Git0xf** [comment]
@2du .......

**Comment by bumabugjebo** [comment]
혹시 당신 Seed0xF 입니까

**Comment by bumabugjebo** [comment]
?

**Comment by Git0xf** [comment]
글쎄요. 이슈와 관련 없는 얘기는 삼가해주시면 감사하겠습니다.

**Comment by Hoto-Cocoa** [comment]
과열로 인해 잠궈두겠습니다. @LiteHell 오시면 처리해주세요.

**Comment by LiteHell** [comment]
#25
