### ISSUE TITLE
문서 star 관련

### ISSUE THREAD

**Issue by alexkoala** [LiteHell/theseed-skin-buma#23]
클릭하면
> 별찜하기:D

해제하면
> 별찜해제;

 라고 뜨는데, 더 적당한 문구는 없나요?

**Comment by Hoto-Cocoa** [comment]
더 나은 문구가 생각나신다면 제안해주시면 감사하겠습니다!

**Comment by alexkoala** [comment]
>Star

>Unstar

사실 저 뒤에 :D 하고 ; 만 없에도 될 것 같네요.

**Comment by bumabugjebo** [comment]
소유자 씨 지금 뭐하는 겁니까

**Comment by bumabugjebo** [comment]
그리고 또 문제 있는데

**Comment by alexkoala** [comment]
?
기여자랑 소유자는 다릅니다.

**Comment by bumabugjebo** [comment]
아 몰라 안녕히 계세요

**Comment by 2du** [comment]
이슈가 없슈? 깔깔

**Comment by bumabugjebo** [comment]
압니다! 일반유져가 댓글 못다니꺼 그소리 한겁니다

**Comment by Hoto-Cocoa** [comment]
다른 메뉴가 다 한국어인데 이것만 영어로 하는건 조금 그렇고요, 이모티콘 빼는건 @LiteHell 어떻게 생각하세요?

**Comment by bumabugjebo** [comment]
bye

**Comment by alexkoala** [comment]
> 다른 메뉴가 다 한국어인데 이것만 영어로 하는건 조금 그렇고요, 이모티콘 빼는건 @LiteHell 어떻게 생각하세요?
@Hoto-Cocoa 북마크, 북마크 해제는 어떤가요?

**Comment by 2du** [comment]
그냥 스타로 합시더

**Comment by alexkoala** [comment]
@2du 한국어로요?

**Comment by 2du** [comment]
@alexkoala 넹

**Comment by alexkoala** [comment]
Unstar는요?

**Comment by Katinor** [comment]
@alexkoala 스타취소로 하는게 어때요

**Comment by 2du** [comment]
@alexkoala 언스타로 합시더

**Comment by kpjhg0124** [comment]
@2du 스타해제는요?

**Comment by wikified** [comment]
反스타

**Comment by LiteHell** [comment]
이모티콘만 빼겠습니다.

**Comment by pseol2190** [comment]
설정 시: "Watch (주시)"
해제 시: "Unwatch (주시 해제)"

**Comment by pseol2190** [comment]
@2du 무슨...

**Comment by pseol2190** [comment]
@2du 
>이슈가 없슈? 깔깔
이게 뭡니까?

**Comment by pseol2190** [comment]
@LiteHell 이모티콘 써도 괜찮을 듯 합니다.
안 되어 있으면: "☆"
되어 있으면: "★"

**Comment by 2du** [comment]
@pseol2190 트롤링요

**Comment by pseol2190** [comment]
제가 조금만 뭐라고 하면 다들 빼애액거리더니(특히 H가) 님이 하는 건 괜찮은가 보네요?

**Comment by Git0xf** [comment]
상관없는 데 불 켜지 말고 이슈에만 집중합시다.

**Comment by pseol2190** [comment]
[반달 복구]
제가 조금만 뭐라고 하면 H가 아주 빼애액거리더니 님이 하는 건 괜찮은가 보네요?
