### ISSUE TITLE
hero 쪽 footer 관련

### ISSUE THREAD

**Issue by alexkoala** [LiteHell/theseed-skin-buma#24]
마우스를 올려야 텍스트가 뜨는데 마우스 안올려도 텍스트를 출력하면 안되나요?

**Comment by pseol2190** [comment]
{{반대|결사}} 애초에 스킨이 그렇게 만들어진 겁니다.

**Comment by yeoncomi** [comment]
@pseol2190 여기는 미디어위키가 아니라 깃헙입니다...

**Comment by pseol2190** [comment]
@yeoncomi 넹 ㅠ
