### ISSUE TITLE
Support r18.wiki

### ISSUE THREAD

**Issue by PlavorSeol** [LiteHell/theseed-skin-buma#31]
[R18위키](https://r18.wiki/) 지원 추가 요청합니다.

**Comment by 2du** [comment]
이미 지원합니다

**Comment by PlavorSeol** [comment]
죄송합니다. NamuFix에 열어야 될 이슈를 실수로 여기에 열었습니다.

**Comment by PlavorSeol** [comment]
[정정합니다.](https://github.com/LiteHell/NamuFix/issues/127)
