### ISSUE TITLE
사문 기여내역 표시 오류

### ISSUE THREAD

**Issue by THESEEDALPHA** [LiteHell/theseed-skin-buma#37]
# 사용환경
 * 브라우저 : Chrome 75.0.3770.142
 * 운영체제 : Windows 8.1

# 버그 설명
알파위키 사문에서 읽기 모드로 되어 있을 때는 별찜 옆에 기여내역이 뜨지만 편집이나 ACL에서는 별찜 옆에 기여내역이 뜨지 않습니다.

**Comment by OtneiV** [comment]
타 스킨에서도 읽기 상태일 때만 표시되는 것으로 보입니다.

**Comment by Fakeness** [comment]
위키에서 값을 안주기 때문에 구현이 까다로울 것 같네요
