### ISSUE TITLE
토론 레스 디자인 관련 문의

### ISSUE THREAD

**Issue by gdl-888** [LiteHell/theseed-skin-buma#42]
# 사용환경
 * 브라우저 : Pale Moon 28.12.0

# 설명

현재 토론 레스의 디자인을 변경하려면 CSS 선택자를 `.<1자리 클래스>[data-v-<해시>]`로 해야 하는데 해시는 계속 변경되므로 선택자를 다음과 같이 부모 노드부터 조금씩 내려가능 방식으로 변경하면 레스의 디자인 변경이 가능합니다.

하지만 (레스 외에도) 의도치 않게 클래스명이 겹치는 경우가 발생하므로 이러한 방식을 사용하실 의향이 있으신지 문의합니다.

.res-wrapper.res-loading .r-head => h2 + div div.r.l.v div.c div.h
.res-wrapper.res-loading .r-body => h2 + div div.r.l.v div.c div.b

.res .r-head => h2 + div div.r div.c div.h
.res .r-head.first-author => h2 + div div.r div.c div.h.f

.res .r-body => h2 + div div.r div.c div.h + div.b
.res .r-body.r-hidden-body => h2 + div div.r div.c div.h + div.b.h
.res.res-type-status .r-body => h2 + div div.r div.c div.h + div.b.s

**Comment by LiteHell** [comment]
없습니다.
