### ISSUE TITLE
최근 변경, 최근토론

### ISSUE THREAD

**Issue by teojeoboja** [LiteHell/theseed-skin-buma#47]
모바일로 부마스킨을 이용할 때 이 두 가지가 보이지 않습니다.
그리고 위키 홈으로 갈 수 있도록 상단에 아이콘도 추가할 필요가 있어보입니다.

**Comment by Tenpower** [comment]
삼성 갤럭시 Wide4(A20)에서 테스트 결과 현재는 해결 된 것으로 보입니다.
