### ISSUE TITLE
[버그]분류랑 text쪽 간격이 "많이" 벌어져 있는 문제

### ISSUE THREAD

**Issue by Tenpower** [LiteHell/theseed-skin-buma#49]
# 사용환경
 * 브라우저 : Chrome 107.0.5304.107
 * 운영체제 : Windows 11 22H2 빌드버전 22621.819

# 설명
![image](https://user-images.githubusercontent.com/94548284/202897575-74848e1b-153d-46b9-8c1d-5198d8f1c240.png)
의도 된 건 아닌 것으로 보여집니다. 나무위키쪽과 더시드위키쪽의 liberty 스킨 혹은 senkawa 스킨과 다르게 분류랑 오른쪽에 text(사진에선 알파위키라 나옵니다.)쪽의 간격이 너무 벌어져 있다고 생각이 듭니다.

**Comment by LiteHell** [comment]
커밋 068d96331580305d5757d5d66efad352492c1b1a 에서 해결됨.
