### ISSUE TITLE
Copyright notice 바꿔주세요

### ISSUE THREAD

**Issue by BunnyMearcat** [LiteHell/theseed-skin-buma#5]
> Contents are available under the CC BY-SA-KR 2.0 Licensed; There could be exceptions if specified or metioned.
창조님께서 쓰신 문구입니다

https://www.alphawiki.org/thread/818yUNcjhxwbvjecPPsTsM

**Comment by pseol2190** [comment]
Content is available under $1 unless otherwise noted.
[MediaWiki:Copyright](http://pseol.urown.cloud:81/exit/MediaWiki:Copyright) 문서에 있는 내용입니다. 미디어위키에서는 이렇게 쓰고 있습니다.

**Comment by pseol2190** [comment]
별도로 명시하지 않은 경우, 내용은 $1에 따라 사용할 수 있습니다.
한국어 버전입니다.

**Comment by LiteHell** [comment]
> Contents are available under the CC BY-SA-KR 2.0 Licensed; There could be exceptions if specified or metioned.
알파위키에 한정하여 위 문구 적용 예정, 알파위키외에서는 아래 문구 적용 예정
> Content is available under the CC BY-SA 4.0 unless otherwise noted.

**Comment by Hoto-Cocoa** [comment]
@pseol2190 굳이 굵음 처리 할 필요도 없어보이고, 미디어위키는 미디어위키지 전 세계 위키의 표준이 아닙니다.

**Comment by BunnyMearcat** [comment]
ㄴ 그냥 인용문 대신 여기서 읽기 쉬우라고 볼드 쓰신 것 같습니다
