### ISSUE TITLE
[버그/건의]문서에서 "읽기"탭 외에 "별찜"탭이 안 보임

### ISSUE THREAD

**Issue by Tenpower** [LiteHell/theseed-skin-buma#52]
# 사용환경
 * 브라우저 : Chrome 107.0.5304.107
 * 운영체제 : Windows 11 22H2 빌드버전 22621.819

# 버그 설명
![image](https://user-images.githubusercontent.com/94548284/202904473-5f375076-9053-4cf3-9c5c-7a8b1a660583.png)
![image](https://user-images.githubusercontent.com/94548284/202904524-bf5c3b1c-7c0e-4071-beab-4dd0d5a5c741.png)

제목이 곧 내용입니다. 사실상 기능 추가 요청입니다. "읽기"탭 외에는 "별찜"탭이 안 보입니다. 다만 이는 senkawa하고 liberty에선 그런 기능이 없으나 기능 추가 해줬으면 좋겠습니다. buma의 사이드 바 탭 부분이 모두 보여야 된다고 생각합니다.

**Comment by LiteHell** [comment]
#37 이랑 중복된 이슈임.
