### ISSUE TITLE
[버그]몇몇 각주 미리보기가 이상하게 보임

### ISSUE THREAD

**Issue by Tenpower** [LiteHell/theseed-skin-buma#53]
# 사용환경
 * 브라우저 : Chrome 107.0.5304.107
 * 운영체제 : Windows 11 22H2 빌드버전 22621.819

# 버그 설명
![image](https://user-images.githubusercontent.com/94548284/202905154-e7a4192b-6fad-4ac3-affc-ab687ae83560.png)
사진과 같이 원인은 모르겠지만 각주번호에 커서를 대면 이상하게 보이는 것이 몇몇 보입니다.

**Comment by Tenpower** [comment]
이 이슈는 그렇게 급한 일도 아니기 때문에 low priority를 달았습니다.

**Comment by Fakeness** [comment]
스킨 문제가 아닌 것으로 보이네요
