### ISSUE TITLE
[건의]ACL되어있을때 편집 탭이 활성화 안 되어있음

### ISSUE THREAD

**Issue by Tenpower** [LiteHell/theseed-skin-buma#54]
# 사용환경
 * 브라우저 : Chrome 107.0.5304.107
 * 운영체제 : Windows 11 22H2 빌드버전 22621.819

# 버그 설명
![image](https://user-images.githubusercontent.com/94548284/202906168-e9e204d2-0070-4892-af42-8bf584e37d30.png)
![image](https://user-images.githubusercontent.com/94548284/202906187-76be45af-779f-4ad8-9737-a803d412fc47.png)
이게 뭔 말이냐면 1번째 사진은 편집 ACL이 잠겨있을때 표시되는 이미지고 2번째 사진은 편집 ACL이 열려있을때 표시되는 이미지 입니다. 

잘 보면 "편집"이라고 뜨는데 편집 ACL이 잠겨있으면 저 탭이 표시가 안 되어있는데 통일성을 위해서 똑같이 해주셨으면 좋겠습니다.

안됨 말고 ㅎ

**Comment by LiteHell** [comment]
편집 ACL이 잠겨있어서 해당 탭이 활성화가 안 된게 아니라, 편집 요청이라서 활성화가 안 된 거 같음.
어려운 건 아니라서, modular_bulma 브랜치 이상 없는거 확인되는 대로 merge한 후 바로 반영하겠음.
