### ISSUE TITLE
[버그]검색탭에서 바로 문서가 들어가지지 않음

### ISSUE THREAD

**Issue by Tenpower** [LiteHell/theseed-skin-buma#55]
# 사용환경
 * 브라우저 : Chrome 107.0.5304.107
 * 운영체제 : Windows 11 22H2 빌드버전 22621.819

# 버그 설명
![image](https://user-images.githubusercontent.com/94548284/202906509-85b0f75a-8d61-495c-8f19-03a747517916.png)
저렇게 치고 아래쪽 자동 완성쪽에 커서 클릭하면 원래 문서에 바로 들어가져야 되는데 안 들어가집니다.
검색 아이콘 클릭하면 문서 들어가집니다.

**Comment by LiteHell** [comment]
솔직히 현 코드가 왜 안 되는지 이해가 안 되긴 하지만, 일단 임시방편의 해결책으로 고치겠습니다.

**Comment by Tenpower** [comment]
수정 안 됨

**Comment by LiteHell** [comment]
PR #80 에서 재수정함.

**Comment by LiteHell** [comment]
재수정해도 안되네... 계속 원인 파악해보겠습니다.

**Comment by Fakeness** [comment]
위키에 반영되었습니다.

**Comment by LiteHell** [comment]
> 위키에 반영되었습니다.

확인했습니다, 감사합니다.
