### ISSUE TITLE
사토 호출박스 안보임

### ISSUE THREAD

**Issue by LiteHell** [LiteHell/theseed-skin-buma#59]

**Comment by Tenpower** [comment]
![image](https://user-images.githubusercontent.com/94548284/202963360-83e0af9d-2845-417b-a51f-f0727758bc8d.png)

Liberty스킨 모습

![image](https://user-images.githubusercontent.com/94548284/202963410-db6dd80f-9554-4aa2-a910-c2f833876ed4.png)

buma스킨 모습

**Comment by Tenpower** [comment]
https://github.com/LiteHell/theseed-skin-buma/blob/master/components/b-notification.vue 
여기 파일 내부에서 문제를 일으키는 것 같습니다.

**Comment by LiteHell** [comment]
> https://github.com/LiteHell/theseed-skin-buma/blob/master/components/b-notification.vue 여기 파일 내부에서 문제를 일으키는 것 같습니다.

네, 확인했고 지금 고치는 중입니다.
