### ISSUE TITLE
테마 색상 변경 요청(위키 별로 개별 설정이 가능한 경우)

### ISSUE THREAD

**Issue by ghost** [LiteHell/theseed-skin-buma#6]
위키 별로 개별 설정이 가능한 경우, 알파위키에 한하여 스킨의 테마 색상을 알파위키의 대표 색상인 #abcdef로 변경해 주시기 바랍니다.

**Comment by BunnyMearcat** [comment]
리버티 스킨처럼요?

**Comment by pseol2190** [comment]
@BunnyMearcat Buma 스킨 상단(현재 #00d1b2가 적용된 부분)을 말하는 겁니다. Liberty 스킨과 아무런 관련이 없습니다.

**Comment by LiteHell** [comment]
계획 없음.
