### ISSUE TITLE
아이콘 안 보임

### ISSUE THREAD

**Issue by LiteHell** [LiteHell/theseed-skin-buma#61]
FontAwesome 아이콘들이 다 안 보임.

**Comment by LiteHell** [comment]
5ed5ebf20b51e317855c479df78b69fa96871f22 에서 수정하긴 했는데 버그가 실제로 고쳐질지는 봐야알 듯.

**Comment by OtneiV** [comment]
![A4A02714-8217-47F1-AC29-42975749B1AF](https://user-images.githubusercontent.com/109079203/203867567-91bd2188-b090-4c99-a07d-8524cbd0100b.jpeg)

대부분 아이콘은 정상적으로 표시되는데 도구, 사용자 도구 아이콘이 보이지 않습니다

**Comment by OtneiV** [comment]
![0987804B-1AA2-4553-BFA9-F1DB57518324](https://user-images.githubusercontent.com/109079203/203868120-cf2a2b8a-fd25-4360-89e0-ad18bd235f36.jpeg)

대부분의 아이콘들이 다시 정상적으로 표시되지만, 도구, 사용자 도구 아이콘이 고쳐지지 않았습니다.

**Comment by OtneiV** [comment]
![image](https://user-images.githubusercontent.com/109079203/203961103-7c7a9c71-738b-41ab-8506-76d07f8ed984.png)

예전에 위와 같이 이런 식으로 표시됐었는데 아이콘 전체가 사라지면서 일부가 다시 복구 되었으나, 도구, 사용자 도구 아이콘이 표시되지 않아 수정해주시면 감사드리겠습니다.

아래는 현재 모습입니다.
![화면 캡처 2022-11-25 192556](https://user-images.githubusercontent.com/109079203/203962989-e6356118-0806-4d1e-aa2d-b9bcbe8fe8c3.png)

**Comment by Tenpower** [comment]
`<buma-font-awesome-icon icon =""> </buma-font-awesome-icon>`
@LiteHell 해당 문법들이 layout.vue에 적용이 안되어있습니다. 21, 91 line을 확인하시면 될 듯 합니다.

**Comment by LiteHell** [comment]
> `<buma-font-awesome-icon icon =""> </buma-font-awesome-icon>` @LiteHell 해당 문법들이 layout.vue에 적용이 안되어있습니다. 21, 91 line을 확인하시면 될 듯 합니다.

그건 b-dropdown.vue에서 받기때문에 그게 아닌 다른 이유이지 않을까 싶습니다.

**Comment by Tenpower** [comment]
![image](https://user-images.githubusercontent.com/94548284/204244046-4bc0dc1d-cb2a-4168-abd8-d3ee2ee3889a.png)

**Comment by LiteHell** [comment]
PR에서 미처 master 브랜치를 머지하지 않아서 생긴 문제. 해결됐으니 다시 닫음.
