### ISSUE TITLE
위쪽 탭 버그

### ISSUE THREAD

**Issue by Tenpower** [LiteHell/theseed-skin-buma#63]
# 사용환경
 * 브라우저 : Firefox Nightly 109.0a1
 * 운영체제 : Windows 11 22H2

# 버그 설명
![image](https://user-images.githubusercontent.com/94548284/203830170-a53b8607-6b20-4232-b38b-8062cf0896ef.png)
![image](https://user-images.githubusercontent.com/94548284/203830221-c68e3358-d210-408b-ab67-37f0d72adfb7.png)
위에는 컴퓨터 아래는 모바일입니다. 탭이 이상하게 버그난듯 합니다.

원래 정상적으로 떠야되는건 다음과 같습니다. https://www.alphawiki.org/w/%ED%8C%8C%EC%9D%BC:097779c66468_Honeycam%202017-12-24%2002-44-31.gif

**Comment by LiteHell** [comment]
6b967b475f8927c4c899c3c9aa329c17c7ae3627 에서 해결됨.
