### ISSUE TITLE
도구 및 사용자 도구 아이콘이 보이지 않음

### ISSUE THREAD

**Issue by OtneiV** [LiteHell/theseed-skin-buma#66]
# 사용환경
 * 브라우저 : Safari 16
 * 운영체제 : iOS 16.1.1

# 버그 설명
![42D08371-C3BB-42C6-9E66-742CE3AAC3EA](https://user-images.githubusercontent.com/109079203/203948119-79862250-c39a-47aa-a6ed-47e76b6d0258.jpeg)

대부분의 아이콘들이 다시 정상적으로 표시되지만, 도구, 사용자 도구 아이콘이 고쳐지지 않았습니다.

**Comment by Tenpower** [comment]
#61 에서 이어집니다. 정상입니다.

**Comment by OtneiV** [comment]
@Tenpower 정상이라는 말씀은 원래 안뜨는건가요?

**Comment by OtneiV** [comment]
![image](https://user-images.githubusercontent.com/109079203/203961103-7c7a9c71-738b-41ab-8506-76d07f8ed984.png)

예전에 이런 식으로 표시됐었는데 아이콘 전체가 사라지면서 같이 사라졌습니다.

**Comment by Tenpower** [comment]
네 주제는 저 이슈랑 같으니 닫으셔두 됩니다. 저기서 이어서 말씀드리면 되요.

**Comment by OtneiV** [comment]
네 확인했습니다.
