### ISSUE TITLE
특수문서 > 특수 문서

### ISSUE THREAD

**Issue by OtneiV** [LiteHell/theseed-skin-buma#68]
# 사용환경
 * 브라우저 : Safari 16
 * 운영체제 : iOS 16.1.1

# 버그 설명
![08844B5F-9B98-487A-8B96-C8056F96DC26](https://user-images.githubusercontent.com/109079203/204138150-971ae13e-0444-4a16-b9c9-2699a6948bc0.jpeg)
위의 특수문서 명칭을 특수 문서로 변경 부탁드립니다.

**Comment by LiteHell** [comment]
이런 맞춤법 오타중에 다른 고칠만한 것들이 더 있나요? 이왕 고칠거 한꺼번에 고치는 게 나아서요.

**Comment by OtneiV** [comment]
더 없는 거 같습니다.
