### ISSUE TITLE
두 편집 간 차이 비교시 삭제된 부분이 표시되지 않습니다.

### ISSUE THREAD

**Issue by pseol2190** [LiteHell/theseed-skin-buma#7]
두 편집 간 차이를 비교하는 화면에서 삭제된 부분이 표시되지 않고 'X' 모양만 표시됩니다.

**Comment by pseol2190** [comment]
그럼 스킨에는 아무 문제 없고(스킨에서 해결할 수 있는 일이 아니고) 사용 환경이 문제라는 건가요?
참고로 제 기기에서만 안 되는 것도 아니고 다른 기기(공용 PC 등)에서도 작동하지 않습니다.

**Comment by LiteHell** [comment]
스킨 버그라고.

**Comment by pseol2190** [comment]
Ah, now I understand.
