### ISSUE TITLE
이전 리버전 볼 시 경고 추가

### ISSUE THREAD

**Issue by LiteHell** [LiteHell/theseed-skin-buma#72]
rev랑 date 체크하면 될 듯함.

**Comment by OtneiV** [comment]
@LiteHell 언제쯤 추가하실 계획이신가요?

**Comment by LiteHell** [comment]
> @LiteHell 언제쯤 추가하실 계획이신가요?

일단 현재 작업중인 다른 이슈들이 먼저 끝난 뒤에 작업이 이루어지지 않을까 싶습니다.

**Comment by Rollable** [comment]
최근 확인 결과 표시되는 것으로 보이며, 이에 따라 CLOSE 요청합니다.

**Comment by Rollable** [comment]
엔진 업데이트로 모든 스킨에서 추가된 듯 합니다.
닫기 요청드립니다.

**Comment by Rollable** [comment]
엔진 업데이트로 모든 스킨에 적용되어 이슈 닫으셔도 될 듯 합니다.
