### ISSUE TITLE
buma 스킨의 버그와 건의들 모음

### ISSUE THREAD

**Issue by Tenpower** [LiteHell/theseed-skin-buma#75]
buma 스킨의 향후 계획 이슈입니다.

넣을 기능들과 이미 해결된 것도 넣었습니다.

- [ ] 기능 추가
  - [ ] 이전 리비전을 볼 시 경고 기능 추가
  - [ ] 문서의 이전 리비전을 볼 시 [주의!] 문구 추가
  - [ ] 토론을 들어 갈 시에 토론 목록 기능 추가
  - [ ] 네임스페이스에 색깔 입히는기능 추가(나무위키: 가 회색같이 보이는 것 똑같이 안하셔두 됩니다.)
  - [ ] 설정 밑에 "라이트 테마", "다크 테마" 선택 여부
  - [ ] 페이지 이동 시 검색 창 초기화 안함을 추가
- [ ] 버그 수정  
  - [ ] 다크 모드 수정(현재 눈이 너무 부십니다.)
  - [ ] 토론 맨 아래쪽 댓글 달기 Tab 표시 문제
  - [ ] 이미지 height 값 문제
  - [ ] 분류랑 text쪽 간격이 "많이" 벌어져 있는 문제
  - [ ] 사용자 문서 기여내역 표시 오류
  - [ ] 검색 탭에서 바로 문서가 들어가지지 않음
  - [ ] 표 너비가 불량
  - [x] 사용자 토론 알림이 안 보임(liberty에선 잘 보이니 버그맞음)
  - [ ] 스크롤 바 표시 문제

**Comment by LiteHell** [comment]
"사용자 문서 기여내역 표시 오류"는 다른 스킨에서도 구현되어 있지 않다는 점을 고려하여, 기능 추가 및 구현으로 올리겠습니다.
