### ISSUE TITLE
임의 문서로 이동하는 버튼 추가

### ISSUE THREAD

**Issue by pseol2190** [LiteHell/theseed-skin-buma#8]
~Buma 스킨 이슈가 너무 많은데 알 게 뭐야~
누르면 임의의 문서로 이동할 수 있는 버튼을 추가해주시기 바랍니다.
Senkawa 스킨 검색 상자 왼쪽에 있는 버튼 및 Liberty 스킨의 '임의문서' 메뉴와 동일한 기능입니다.
~[RandomPage](https://www.alphawiki.org/RandomPage) 특수 문서와는 다르다! [RandomPage](https://www.alphawiki.org/RandomPage) 특수 문서와는!~

**Comment by LiteHell** [comment]
취소선 개그 지양해주세요. 안 웃겨요.

**Comment by BunnyMearcat** [comment]
ㄴ 뭐 싫다는 사람을 싫은거고 좋다는 사람은 좋다는 거긴 한데 뭐 주인이 말라면 말아야죠
리버티는 도구>>RandomPage가 있긴 한데 그걸 고려하면 되지 않을까..

**Comment by pseol2190** [comment]
@BunnyMearcat **[RandomPage](https://www.alphawiki.org/RandomPage) 특수 문서 아니라고 위에서 분명히 말했습니다.**
~그리고 누가 그렇게 말하면 취소선 안 쓸 줄 알고?~

**Comment by Hoto-Cocoa** [comment]
재미 없습니다. RandomPage는 보통 특수문서로 보는게 맞습니다.

**Comment by BunnyMearcat** [comment]
@pseol2190 취소선이라 뻥인줄 알았죠.
그거 '''theseed.io/random''' 이런식으로 쓸 수 있습니다.

**Comment by Hoto-Cocoa** [comment]
임의의 문서로 이동한다가 설마 검색창에 적은 문서로 바로 이동하는 그 버튼 말씀하시는건 아니겠죠? 보통 그건 특정 문서라고 표현합니다.

**Comment by LiteHell** [comment]
대충 뭘 원하는 지 알겠으니까 싸우지 마세요.

**Comment by pseol2190** [comment]
@Hoto-Cocoa 그게 맞습니다.
저도 [RandomPage](https://www.alphawiki.org/RandomPage) 관련해서 언급할 때는 특수 문서라고 이야기합니다. 근데 여기서 요청하는 것은 **그게 아니니까** 아니라고 말하는 거죠.

**Comment by Hoto-Cocoa** [comment]
단어 선택이 잘못되어서 발생한 문제네요.

**Comment by Hoto-Cocoa** [comment]
볼드체 그만 쓰세요.

**Comment by pseol2190** [comment]
**볼드체 사용은 내 권리입니다. 당신 멋대로 제한하려 하지 마세요.**

**Comment by BunnyMearcat** [comment]
둘다 진정하세요 볼드체 사용은 좋은데 화난 말투로 인식될 수 있어서 권고의 목적으로 보입니다 말려면 마시어도 됩니다

**Comment by pseol2190** [comment]
아니 지가 뭔데 계속 이래라 저래라야

**Comment by yeoncomi** [comment]
@pseol2190 그만하세요

**Comment by Hoto-Cocoa** [comment]
왜 레비님 트위터가 여기서 나오는지... 뭐 마음대로 하시던가요.

**Comment by LiteHell** [comment]
싸우지마세요.

**Comment by pseol2190** [comment]
@yeoncomi [당신이나 그만하세요](https://www.alphawiki.org/w/너나 잘하세요)
@LiteHell 죄송합니다. 제가 이슈를 남겼는데 갑자기 제3자가 끼어들다 보니 이렇게 마찰이 발생하게 되었네요...

**Comment by Hoto-Cocoa** [comment]
원래 깃허브 이슈트래커는 제3자가 없이 누구나 참여 가능한 토론입니다...
