### ISSUE TITLE
favicon 못 불러옴

### ISSUE THREAD

**Issue by Tenpower** [LiteHell/theseed-skin-buma#85]
# 사용환경
 * 브라우저 : Firefox Nightly 109.0a1 (2022-11-28일 빌드버전)
 * 운영체제 : Windows 11 22H2 Build 22621.819

# 버그 설명
![image](https://user-images.githubusercontent.com/94548284/204517125-3615f055-7444-4f70-ab87-1febf3a665e8.png)
liberty스킨에선 favicon이 뜨나 buma에선 안 뜨는 문제 콘솔 창 열어보니 해당 오류인듯합니다.
![image](https://user-images.githubusercontent.com/94548284/204517294-59eeaff1-fc2e-43ef-82ba-7261ce339366.png)
404 Not Found로 뱉어내고 있습니다.

**Comment by LiteHell** [comment]
favicon은 스킨에서 담당하지 않고, 리버티 스킨에서도 관련 코드를 본 적이 없습니다. namu한테 가서 여쭤보세요.
