### ISSUE TITLE
기여내역 탭만 항상 펼쳐져 있습니다

### ISSUE THREAD

**Issue by pseol2190** [LiteHell/theseed-skin-buma#9]
다른 탭은 활성화되어 있을 때만 펼쳐지는데 기여내역 탭만 항상 펼쳐져 있는 현상이 발생합니다.
![사용자:LiteHell](https://user-images.githubusercontent.com/39310079/42791996-4026d15a-89ae-11e8-8d10-c6d43d3daa80.png)

**Comment by pseol2190** [comment]
~의도했을 수도 있겠죠... 기여내역이 중요하다 보니까 그 부분을 강조하려면...~
+기여내역, 리다이렉트, Facebook, Twitter 탭도 다른 탭처럼 읽기 탭이 활성화되었을 때뿐만 아니라 편집, 토론, 이동, 삭제, 역링크, 역사, ACL 화면에서도 탭이 표시되도록 수정해 주실 수 있습니까?

**Comment by Tenpower** [comment]
Thinking

**Comment by LiteHell** [comment]
@pseol2190 그건 별도의 이슈를 생성해주세요.
