### ISSUE TITLE
표에 사진 첨부하고 보면 이상하게 나옵니다.

### ISSUE THREAD

**Issue by Tenpower** [LiteHell/theseed-skin-buma#98]
![image](https://user-images.githubusercontent.com/94548284/205502936-50860b11-862d-4a35-af86-7c2bef7126fc.png)
buma스킨의 표 모습입니다.

![image](https://user-images.githubusercontent.com/94548284/205502957-26fd71bd-0287-440e-8264-d9206320b00e.png)
liberty-alpha스킨의 표 모습입니다.

사진이 위로 올라 가있습니다.

**Comment by OtneiV** [comment]
![0C078B34-152D-4888-83AF-E3A285AFC1B1](https://user-images.githubusercontent.com/109079203/205517350-8aeac5d1-fdfe-452d-8d9e-4e0f9fea74c8.jpeg)

텍스트에서도 동일한 현상이 발생합니다.
