### ISSUE TITLE
관리자 메뉴 아이콘 적용 문의

### ISSUE THREAD

**Issue by Rollable** [LiteHell/theseed-skin-buma#99]
# 사용환경
 * 브라우저 : Chrome 109.0.5414.7
 * 운영체제 : Windows 11

# 버그 설명
과거에는 아래 사진처럼 관리자 메뉴에도 아이콘이 적용되어 있었으나 현재는 아이콘이 사라졌습니다.
![image](https://user-images.githubusercontent.com/109079203/206850468-9f98fe16-87ae-49af-8541-c04a101cf087.png)

**Comment by LiteHell** [comment]
가능하지만 고민해야 할 점이 하나 있습니다.

엔진에서 제공하는 메뉴 아이콘 속성값은 [Ionicons v4](https://ionic.io/ionicons/v4) 라이브러리를 기준으로 제공합니다. senkawa 스킨이 해당 라이브러리를 이용합니다. 반면에 buma 스킨과 [liberty 스킨](https://github.com/namu-theseed/theseed-skin-liberty)은 [Fontawesome](https://fontawesome.com) 아이콘 라이브러리를 사용합니다.

그렇기 때문에 스킨에서 엔진이 제공하는 아이콘 속성값을 바로 이용하면 스킨내 다른 아이콘과 어느정도의 디자인적 괴리감이 발생할 수 있습니다. 그러므로 이 점을 어떻게 해결할 지 고민하는 데 시간이 약간 걸릴 것 같습니다.

**Comment by OtneiV** [comment]
추가적으로 표시될 때 현재는 **ACL Group**, **권한**, **로그인 기록 조회**로 표시되는데 이 부분을 예전처럼 **[관리] ACL Group**, **[관리] 권한 부여**, **[관리] 로그인 기록 조회**로 뜰 수 있게 변경하여 주시면 감사드리겠습니다.

**Comment by LiteHell** [comment]
> 추가적으로 표시될 때 현재는 **ACL Group**, **권한**, **로그인 기록 조회**로 표시되는데 이 부분을 예전처럼 **[관리] ACL Group**, **[관리] 권한 부여**, **[관리] 로그인 기록 조회**로 뜰 수 있게 변경하여 주시면 감사드리겠습니다.

엔진에서 제공하는 해당 데이터가 관리 메뉴용으로만 쓰인다는 보장이 없으므로 해당 요청은 받아들일 의향이 없습니다.

**Comment by Rollable** [comment]
최근 하트 아이콘이 추가된 것으로 보여 다시 엽니다.

**Comment by navyCarpet** [comment]
네, 하트 아이콘으로 제가 추가하였습니다.

**Comment by navyCarpet** [comment]
요구 사항을 명확하게 설명해 주세요

**Comment by Rollable** [comment]
제가 처음 보여드린 아이콘처럼 추가해주실 수 있으실까요?

**Comment by navyCarpet** [comment]
LiteHell 님이 말씀하신 것처럼 괴리감이 발생할 수 있을 것 같아 일괄적으로 하트 아이콘을 적용한 것이긴 한데, espejo에서도 추가 menu의 아이콘은 ionicons를 사용하고 있고 막상 적용해보니 괴리감이 크게 안느껴지는 것 같긴 하네요
